### ISSUE TITLE
Environment setup instructions

### ISSUE THREAD

**Issue by shea-parkes** [milliman/SOA_PAS_CrediblePredictiveModels#1]
Thanks for getting this up here so swiftly.

Could you add a brief note about what packages are utilized so users know what they'll need to install?

This could perhaps take the form of the output of ~`sessionInfo()` so they can see what version of R was used as well...

**Comment by MKullowatz** [comment]
I created the file "EnvironmentInformation", copied from a sessionInfo() call to my console.

**Comment by shea-parkes** [comment]
It might be nice to link to that file from the readme (or just embed the contents in there), but I agree the information is available.  Thanks!
